Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Breadlesscode.NodeTypes.Folder':
            - 'NodeTypes/*/*'
    fusion:
      autoInclude:
        Breadlesscode.NodeTypes.Folder: true
